Environment: production
redis:
  Addr: redis:6379
  Password: password
  DB: 0
postgres:
  host: db
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
  sslmode: disable
gin:
  mode: debug
  port: ":8000"
jwt:
  secret: "123465798"
  refSecret: "132654789"
  expire: 500
  RTexpire: 5000
user:
  MinIdentitiy: 1000000000000
  MaxIdentitiy: 9999999999999
course:
  MinIdentitiy: 1000000000000
  MaxIdentitiy: 9999999999999